version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tenpo_postgres
    restart: always
    environment:
      POSTGRES_DB: tenpo_db
      POSTGRES_USER: tenpo_user
      POSTGRES_PASSWORD: tenpo_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tenpo_network

networks:
  tenpo_network:
    driver: bridge

volumes:
  postgres_data:
