services:
  postgres:
    image: postgres:15
    container_name: tenpo_postgres
    restart: always
    environment:
      POSTGRES_DB: tenpo_db
      POSTGRES_USER: tenpo_user
      POSTGRES_PASSWORD: tenpo_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tenpo_network

  api:
    image: onad/tenpo-api:latest
    container_name: tenpo_api
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tenpo_db
      SPRING_DATASOURCE_USERNAME: tenpo_user
      SPRING_DATASOURCE_PASSWORD: tenpo_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - tenpo_network

networks:
  tenpo_network:
    driver: bridge

volumes:
  postgres_data:
